name: forumcopilot_flutter
description: "ForumCopilot"
publish_to: 'none'
version: 0.6.0+34

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.1
  forumcopilot_sdk: 
    path: ./packages/forumcopilot_sdk
  xenforo_core: 
    path: ./packages/xenforo_core 
  xml: ^6.3.0
  dart_mappable: ^4.3.1
  get: ^4.7.3
  timeago: ^3.7.0
  flutter_bbcode: ^1.5.1
  url_launcher: ^6.2.5
  infinite_scroll_pagination: ^5.0.0
  photo_view: ^0.15.0
  dio: ^5.4.0
  visibility_detector: ^0.4.0+2
  google_fonts: ^8.0.1
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  flutter_image_compress: ^2.3.0
  mime_type: ^1.0.1
  saver_gallery: ^4.1.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.2.0
  html: ^0.15.6
  html_unescape: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_inappwebview: ^6.1.5
  build_runner: ^2.10.4
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^20.1.0
  uuid: ^4.5.2
  package_info_plus: ^8.3.0
  passkeys: ^2.17.4
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/forumcopiloticon_1024.png
  - assets/forumcopiloticon_256.png
  - assets/splash.png
  - assets/main_background.png
  - assets/forum_header_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/forumcopiloticon_1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/forumcopiloticon_1024.png"
  # iOS adaptive icons
  ios_content_mode: scaleAspectFit
