#!/usr/bin/env python3
"""Generate app_nl.arb from app_en.arb with Dutch translations."""
import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
L10N_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), 'lib', 'l10n')
EN_ARB = os.path.join(L10N_DIR, 'app_en.arb')
NL_ARB = os.path.join(L10N_DIR, 'app_nl.arb')

# English -> Dutch translations (placeholders like {domain}, {error} kept as-is)
TRANSLATIONS = {
    "Forum App": "Forum App",
    "Login": "Inloggen",
    "Username": "Gebruikersnaam",
    "Password": "Wachtwoord",
    "Forgot password?": "Wachtwoord vergeten?",
    "Please enter your username": "Voer uw gebruikersnaam in",
    "Please enter your password": "Voer uw wachtwoord in",
    "Your username and password will be sent to {domain}": "Uw gebruikersnaam en wachtwoord worden naar {domain} gestuurd",
    "Create Account": "Account aanmaken",
    "Already have an account? ": "Heeft u al een account? ",
    "Log In": "Inloggen",
    "Continue": "Doorgaan",
    "Registration Not Available": "Registratie niet beschikbaar",
    "Registration is currently not available. The forum may be closed or registration may be disabled.": "Registratie is momenteel niet beschikbaar. Het forum kan gesloten zijn of registratie kan zijn uitgeschakeld.",
    "Web Registration Required": "Webregistratie vereist",
    "This forum requires registration through the web browser. Please click the button below to open the registration page.": "Dit forum vereist registratie via de webbrowser. Klik op de knop hieronder om de registratiepagina te openen.",
    "Open Registration Page": "Registratiepagina openen",
    "Loading additional fields...": "Extra velden laden...",
    "Please select your date of birth": "Selecteer uw geboortedatum",
    "Please enter your location": "Voer uw locatie in",
    "Please indicate your email preference": "Geef uw e-mailvoorkeur op",
    "Please fill in all required fields": "Vul alle verplichte velden in",
    "Please accept the Terms of Service": "Accepteer de servicevoorwaarden",
    "Please accept the Privacy Policy": "Accepteer het privacybeleid",
    "Registration Error": "Registratiefout",
    "Registration failed. Please check your information.": "Registratie mislukt. Controleer uw gegevens.",
    "Registration failed. Please try again.": "Registratie mislukt. Probeer het opnieuw.",
    "Registration Info": "Registratiegegevens",
    "Open Website": "Website openen",
    "Could not open the forum website. Please try visiting: {url}": "Kon de forumwebsite niet openen. Probeer: {url}",
    "Registration successful! Please check your email to confirm your account before logging in.": "Registratie geslaagd! Controleer uw e-mail om uw account te bevestigen voordat u inlogt.",
    "Registration successful! Your account is pending approval. You will be notified when your account is approved.": "Registratie geslaagd! Uw account wacht op goedkeuring. U wordt op de hoogte gesteld wanneer uw account is goedgekeurd.",
    "Registration successful! You have been automatically logged in.": "Registratie geslaagd! U bent automatisch ingelogd.",
    "Welcome!": "Welkom!",
    "Registration Successful": "Registratie geslaagd",
    "Please log in with your new account.": "Log in met uw nieuwe account.",
    "Forgot Password": "Wachtwoord vergeten",
    "Username or Email": "Gebruikersnaam of e-mail",
    "Please enter your username or email": "Voer uw gebruikersnaam of e-mail in",
    "Send Reset Link": "Resetlink verzenden",
    "Reset Link Sent": "Resetlink verzonden",
    "Password reset instructions have been sent to your registered email address.": "Instructies voor het resetten van uw wachtwoord zijn naar uw geregistreerde e-mailadres gestuurd.",
    "Reset Failed": "Reset mislukt",
    "Unable to send reset link. Please try again.": "Kon resetlink niet verzenden. Probeer het opnieuw.",
    "An error occurred while sending the reset link. Please check your connection and try again.": "Er is een fout opgetreden bij het verzenden van de resetlink. Controleer uw verbinding en probeer het opnieuw.",
    "Error": "Fout",
    "OK": "OK",
    "Retry": "Opnieuw",
    "Copy to Clipboard": "Kopiëren naar klembord",
    "Copied": "Gekopieerd",
    "Error message copied to clipboard": "Foutbericht gekopieerd naar klembord",
    "Dismiss": "Sluiten",
    "Cancel": "Annuleren",
    "Try Again": "Opnieuw proberen",
    "Get Help": "Hulp krijgen",
    "Something went wrong": "Er is iets misgegaan",
    "An unexpected error occurred. Please try again.": "Er is een onverwachte fout opgetreden. Probeer het opnieuw.",
    "No Internet Connection": "Geen internetverbinding",
    "Please check your internet connection and try again.": "Controleer uw internetverbinding en probeer het opnieuw.",
    "Authentication Required": "Authenticatie vereist",
    "Please log in to continue.": "Log in om door te gaan.",
    "Forum Error": "Forumfout",
    "An error occurred": "Er is een fout opgetreden",
    "Your account is pending approval. You can browse the forum but cannot post until a moderator approves your account.": "Uw account wacht op goedkeuring. U kunt het forum bekijken maar niet posten tot een moderator uw account goedkeurt.",
    "Please check your email to confirm your account. Click the confirmation link in the email we sent you.": "Controleer uw e-mail om uw account te bevestigen. Klik op de bevestigingslink in de e-mail die we u hebben gestuurd.",
    "Please check your new email address to confirm the change. Your old email will remain active until you confirm the new one.": "Controleer uw nieuwe e-mailadres om de wijziging te bevestigen. Uw oude e-mail blijft actief tot u de nieuwe bevestigt.",
    "Your email address appears to be invalid or is bouncing emails. Please update your email address in account settings.": "Uw e-mailadres lijkt ongeldig of weigert e-mails. Werk uw e-mailadres bij in de accountinstellingen.",
    "Your account has been disabled. Please contact an administrator for assistance.": "Uw account is uitgeschakeld. Neem contact op met een beheerder voor hulp.",
    "Your account registration was rejected. Please contact an administrator for more information.": "Uw registratie is afgewezen. Neem contact op met een beheerder voor meer informatie.",
    "Welcome to Forum Copilot!": "Welkom bij Forum Copilot!",
    "You have been successfully logged out": "U bent succesvol uitgelogd",
    "Your account status requires attention. Please contact an administrator if you have questions.": "Uw accountstatus vereist aandacht. Neem contact op met een beheerder bij vragen.",
    "Update Email": "E-mail bijwerken",
    "Resend": "Opnieuw verzenden",
    "No Latest Topics": "Geen nieuwste onderwerpen",
    "There are no recent topics to display. Check back later for new discussions.": "Er zijn geen recente onderwerpen om weer te geven. Kom later terug voor nieuwe discussies.",
    "Sign in to view latest topics": "Log in om nieuwste onderwerpen te bekijken",
    "You need to be signed in to view latest topics": "U moet ingelogd zijn om nieuwste onderwerpen te bekijken",
    "No Unread Topics": "Geen ongelezen onderwerpen",
    "There are no unread topics. Check back later for new discussions.": "Er zijn geen ongelezen onderwerpen. Kom later terug voor nieuwe discussies.",
    "You're all caught up!": "U bent helemaal bij!",
    "Sign in to view unread topics": "Log in om ongelezen onderwerpen te bekijken",
    "You need to be signed in to view your unread topics": "U moet ingelogd zijn om uw ongelezen onderwerpen te bekijken",
    "No Subscribed Topics": "Geen geabonneerde onderwerpen",
    "You did not subscribe to any topics. Tap the star button on a topic to subscribe and receive notifications for new updates.": "U heeft zich op geen onderwerpen geabonneerd. Tik op de ster bij een onderwerp om te abonneren en meldingen te ontvangen.",
    "Sign in to view subscribed topics": "Log in om geabonneerde onderwerpen te bekijken",
    "You need to be signed in to view your subscribed topics": "U moet ingelogd zijn om uw geabonneerde onderwerpen te bekijken",
    "No Participated Topics": "Geen onderwerpen waaraan u hebt deelgenomen",
    "Topics that you have participated in will be shown here.": "Onderwerpen waaraan u hebt deelgenomen worden hier getoond.",
    "Sign in to view participated topics": "Log in om onderwerpen waaraan u hebt deelgenomen te bekijken",
    "You need to be signed in to view topics you have participated in": "U moet ingelogd zijn om onderwerpen waaraan u hebt deelgenomen te bekijken",
    "Latest": "Nieuwste",
    "Unread": "Ongelezen",
    "Subscribed": "Geabonneerd",
    "Participated": "Deelgenomen",
    "Connection timed out. The site may be down or unreachable.": "Verbinding time-out. De site kan offline of onbereikbaar zijn.",
    "Failed to connect to site. The site may be down or unreachable.": "Kon geen verbinding maken met de site. De site kan offline of onbereikbaar zijn.",
    "Connection Failed": "Verbinding mislukt",
    "Failed to connect to {siteName}": "Kon geen verbinding maken met {siteName}",
    "Loading...": "Laden...",
    "New Conversation": "Nieuw gesprek",
    "New Message": "Nieuw bericht",
    "App Settings": "App-instellingen",
    "Search Sites": "Sites zoeken",
    "Language": "Taal",
    "System Default": "Systeemstandaard",
    "Follow system language": "Systeemtaal volgen",
    "All": "Alles",
    "Topics Only": "Alleen onderwerpen",
    "Titles Only": "Alleen titels",
    "Failed to share topic: {error}": "Kon onderwerp niet delen: {error}",
    "Please login to {action} this thread": "Log in om {action} dit onderwerp",
    "subscribe to": "abonneren op",
    "unsubscribe from": "abonnement opzeggen van",
    "Failed to {action} thread": "Kon {action} onderwerp niet",
    "You cannot reply to this thread": "U kunt niet op dit onderwerp reageren",
    "Please wait for the thread to load": "Wacht tot het onderwerp is geladen",
    "Soft Delete": "Zacht verwijderen",
    "Post can be restored later": "Bericht kan later worden hersteld",
    "Hard Delete": "Definitief verwijderen",
    "Post will be permanently deleted": "Bericht wordt permanent verwijderd",
    "Reason for deletion": "Reden voor verwijdering",
    "Enter the reason for deleting this post": "Voer de reden voor het verwijderen van dit bericht in",
    "Please enter a reason for deletion": "Voer een reden voor verwijdering in",
    "Report Post": "Bericht melden",
    "Please provide a reason for reporting this post.": "Geef een reden op voor het melden van dit bericht.",
    "Reason": "Reden",
    "Enter the reason for reporting this post": "Voer de reden voor het melden van dit bericht in",
    "Please enter a reason": "Voer een reden in",
    "Submit Report": "Melding verzenden",
    "Selected actions:": "Geselecteerde acties:",
    "This action cannot be undone.": "Deze actie kan niet ongedaan worden gemaakt.",
    "Participants": "Deelnemers",
    "{username} has been invited to the conversation": "{username} is uitgenodigd voor het gesprek",
    "Error inviting user: {error}": "Fout bij uitnodigen van gebruiker: {error}",
    "New Topic": "Nieuw onderwerp",
    "Mark Read": "Als gelezen markeren",
    "Report User": "Gebruiker melden",
    "Please select a reason for reporting this user.": "Selecteer een reden voor het melden van deze gebruiker.",
    "Spam or advertising": "Spam of reclame",
    "Harassment or bullying": "Intimidatie of pesten",
    "Inappropriate content": "Ongepaste inhoud",
    "Impersonation or fake account": "Impersonatie of nepaccount",
    "Other (please specify)": "Anders (geef op)",
    "Please specify the reason": "Geef de reden op",
    "Enter the reason for reporting this user": "Voer de reden voor het melden van deze gebruiker in",
    "Please select a reason": "Selecteer een reden",
    "Ban User": "Gebruiker blokkeren",
    "Unban User": "Blokkering opheffen",
    "Please select a reason for banning {username}": "Selecteer een reden voor het blokkeren van {username}",
    "Violation of community guidelines": "Overtreding van de communityrichtlijnen",
    "Harassment or abusive behavior": "Intimidatie of misbruik",
    "Posting inappropriate content": "Plaatsen van ongepaste inhoud",
    "Account compromise or security issue": "Accountcompromittering of beveiligingsprobleem",
    "Enter the reason for banning this user": "Voer de reden voor het blokkeren van deze gebruiker in",
    "Ban until": "Blokkeren tot",
    "Select date": "Selecteer datum",
    "More options": "Meer opties",
    "Leave conversation": "Gesprek verlaten",
    "Report conversation": "Gesprek melden",
    "Topic closed": "Onderwerp gesloten",
    "Topic opened": "Onderwerp geopend",
    "Topic stickied": "Onderwerp vastgezet",
    "Topic unstickied": "Onderwerp losgemaakt",
    "Cannot edit this message: {error}": "Dit bericht kan niet worden bewerkt: {error}",
    "Confirm Spam Clean": "Spam opruimen bevestigen",
    "Handle Threads": "Onderwerpen afhandelen",
    "Delete Messages": "Berichten verwijderen",
    "Delete Conversations": "Gesprekken verwijderen",
    "My Forums": "Mijn forums",
    "Recently Visited": "Recent bezocht",
    "Explore": "Ontdekken",
    "Forum Copilot": "Forum Copilot",
    "No conversations": "Geen gesprekken",
    "You have no conversations yet. Start a new conversation to begin messaging.": "U heeft nog geen gesprekken. Start een nieuw gesprek om te beginnen.",
    "Image saved to gallery!": "Afbeelding opgeslagen in galerij!",
    "Failed to save image: {error}": "Kon afbeelding niet opslaan: {error}",
    "User Profile": "Gebruikersprofiel",
    "Delete Post": "Bericht verwijderen",
    "Login Required": "Inloggen vereist",
    "Spam Cleaner": "Spam opruimer",
    "Send Message": "Bericht verzenden",
    "Member Since": "Lid sinds",
    "Last Activity": "Laatste activiteit",
    "Likes Received": "Ontvangen likes",
    "Likes Given": "Gegeven likes",
    "Show More": "Meer tonen",
    "Clean Spam": "Spam opruimen",
    "Failed to save message": "Kon bericht niet opslaan",
    "Failed to save conversation": "Kon gesprek niet opslaan",
    "Failed to save setting": "Kon instelling niet opslaan",
    "Failed to save post": "Kon bericht niet opslaan",
    "Error loading sites: {error}": "Fout bij laden van sites: {error}",
    "Connecting to {domainName}...": "Verbinden met {domainName}...",
    "Members": "Leden",
    "All Members": "Alle leden",
    "Online": "Online",
    "No members found": "Geen leden gevonden",
    "Search for members": "Leden zoeken",
    "Enter a username to find forum members": "Voer een gebruikersnaam in om forumleden te vinden",
    "No members are currently online": "Er zijn momenteel geen leden online",
    "Enter username to search...": "Voer gebruikersnaam in om te zoeken...",
    "Lookup Members": "Leden opzoeken",
    "Add Members": "Leden toevoegen",
    "Members added successfully": "Leden succesvol toegevoegd",
    "Error adding members: {error}": "Fout bij toevoegen van leden: {error}",
    "Failed to load online users": "Kon online gebruikers niet laden",
    "No users online": "Geen gebruikers online",
    "{count} Members": "{count} leden",
    "No subject": "Geen onderwerp",
    "Search": "Zoeken",
    "Logout": "Uitloggen",
    "Are you sure you want to logout?": "Weet u zeker dat u wilt uitloggen?",
    "Register": "Registreren",
    "Sign In": "Inloggen",
    "Mark Forum Read": "Forum als gelezen markeren",
    "Notification Test": "Meldingstest",
    "Forum": "Forum",
    "Profile": "Profiel",
    "Messages": "Berichten",
    "Add": "Toevoegen",
    "Delete": "Verwijderen",
    "Delete Message": "Bericht verwijderen",
    "Are you sure you want to delete this message?": "Weet u zeker dat u dit bericht wilt verwijderen?",
    "Failed to delete message: {error}": "Kon bericht niet verwijderen: {error}",
    "Deleting post...": "Bericht verwijderen...",
    "Failed to unlike post: {error}": "Kon bericht niet unliken: {error}",
    "Failed to like post: {error}": "Kon bericht niet liken: {error}",
    "Failed to thank post: {error}": "Kon bericht niet bedanken: {error}",
    "Sign in to view messages": "Log in om berichten te bekijken",
    "You need to be signed in to view your conversations.": "U moet ingelogd zijn om uw gesprekken te bekijken.",
    "Error loading conversations: {error}": "Fout bij laden van gesprekken: {error}",
    "Failed to leave conversation: {error}": "Kon gesprek niet verlaten: {error}",
    "Error loading more conversations: {error}": "Fout bij laden van meer gesprekken: {error}",
    "Error loading more messages: {error}": "Fout bij laden van meer berichten: {error}",
    "Invite Message (optional)": "Uitnodigingsbericht (optioneel)",
    "I would like to add you to this conversation.": "Ik wil u aan dit gesprek toevoegen.",
    "Search failed": "Zoeken mislukt",
    "Try searching with a different username": "Probeer te zoeken met een andere gebruikersnaam",
    "No sites found.": "Geen sites gevonden.",
    "User information not available": "Gebruikersinformatie niet beschikbaar",
    "Birthday": "Verjaardag",
    "Posts": "Berichten",
    "Following": "Volgend",
    "Followers": "Volgers",
    "About": "Over",
    "Location": "Locatie",
    "Website": "Website",
    "Signature": "Handtekening",
    "Next": "Volgende",
    "Permanent": "Permanent",
    "Temporary": "Tijdelijk",
    "Set the ban duration for {username}": "Stel de blokkeerduur in voor {username}",
    "Please select an end date for temporary ban": "Selecteer een einddatum voor tijdelijke blokkering",
    "Back": "Terug",
    "Unban": "Blokkering opheffen",
    "Confirm": "Bevestigen",
    "Spam Clean {username}": "Spam opruimen {username}",
    "Select the actions to perform:": "Selecteer de uit te voeren acties:",
    "Move or delete threads based on admin settings": "Verplaats of verwijder onderwerpen op basis van beheerderinstellingen",
    "Message updated successfully": "Bericht succesvol bijgewerkt",
    "Error: {error}": "Fout: {error}",
    "Failed to remove attachment: {error}": "Kon bijlage niet verwijderen: {error}",
    "Failed to load message: {error}": "Kon bericht niet laden: {error}",
    "Edit Message": "Bericht bewerken",
    "Remove Attachment": "Bijlage verwijderen",
    "Are you sure you want to remove this attachment?": "Weet u zeker dat u deze bijlage wilt verwijderen?",
    "None": "Geen",
    "Attach File": "Bestand bijvoegen",
    "Upload Image": "Afbeelding uploaden",
    "Formatting": "Opmaak",
    "Bold": "Vet",
    "Italic": "Cursief",
    "Underline": "Onderstreept",
    "Strikethrough": "Doorgehaald",
    "Link": "Link",
    "Image": "Afbeelding",
    "Video": "Video",
    "Quote": "Citaat",
    "Code": "Code",
    "Spoiler": "Spoiler",
    "Bullet List": "Opsomming",
    "Numbered List": "Genummerde lijst",
    "List Item": "Lijstitem",
    "Participants ({count})": "Deelnemers ({count})",
    "Mark as unread": "Als ongelezen markeren",
    "Invite": "Uitnodigen",
    "Welcome Back": "Welkom terug",
    "Sign in to access your profile and manage your account": "Log in om uw profiel te openen en uw account te beheren",
    "Enter your username": "Voer uw gebruikersnaam in",
    "Enter your password": "Voer uw wachtwoord in",
    "Don't have an account?": "Heeft u geen account?",
    "Enter keywords to search topics...": "Voer zoekwoorden in om onderwerpen te zoeken...",
    "Please fill in all required fields": "Vul alle verplichte velden in",
    "Undelete": "Verwijdering ongedaan maken",
    "You need to be signed in to view your unread topics.": "U moet ingelogd zijn om uw ongelezen onderwerpen te bekijken.",
    "You need to be signed in to view your subscribed topics.": "U moet ingelogd zijn om uw geabonneerde onderwerpen te bekijken.",
    "You need to be signed in to view topics you have participated in.": "U moet ingelogd zijn om onderwerpen waaraan u hebt deelgenomen te bekijken.",
    "You need to be signed in to view latest topics.": "U moet ingelogd zijn om nieuwste onderwerpen te bekijken.",
    "Refresh": "Vernieuwen",
    "Share": "Delen",
    "View on Web": "Bekijken op web",
    "Unlock": "Ontgrendelen",
    "Lock": "Vergrendelen",
    "Stick": "Vastzetten",
    "Unstick": "Losmaken",
    "Reply": "Beantwoorden",
    "Reacted by": "Gereageerd door",
    "Enter keywords to find topics and posts": "Voer zoekwoorden in om onderwerpen en berichten te vinden",
    "Enter keywords or domain to find forums": "Voer zoekwoorden of domein in om forums te vinden",
    "Enter keywords or domain names to find forums": "Voer zoekwoorden of domeinnamen in om forums te vinden",
    "Follow system theme": "Systeemthema volgen",
    "Appearance": "Weergave",
    "Light": "Licht",
    "Dark": "Donker",
    "version {version} ({buildNumber})": "versie {version} ({buildNumber})",
    "Forum Settings": "Foruminstellingen",
    "No settings available": "Geen instellingen beschikbaar",
    "Settings categories will appear here when available.": "Instellingcategorieën verschijnen hier wanneer beschikbaar.",
    "Unable to Load Profile": "Kon profiel niet laden",
    "BANNED": "GEBLOKKEERD",
    "Report submitted successfully": "Melding succesvol verzonden",
    "Failed to submit report": "Kon melding niet verzenden",
    "Search for forums": "Forums zoeken",
    "Search Forums": "Forums zoeken",
    "Delete Topic": "Onderwerp verwijderen",
    "Topic can be restored later": "Onderwerp kan later worden hersteld",
    "Topic will be permanently deleted": "Onderwerp wordt permanent verwijderd",
    "Enter the reason for deleting this topic": "Voer de reden voor het verwijderen van dit onderwerp in",
    "Please enter a reason for deletion": "Voer een reden voor verwijdering in",
    "Please select an end date": "Selecteer een einddatum",
    "User banned successfully": "Gebruiker succesvol geblokkeerd",
    "Failed to ban user": "Kon gebruiker niet blokkeren",
    "User unbanned successfully": "Gebruiker succesvol gedeblokkeerd",
    "Failed to unban user": "Kon blokkering niet opheffen",
    "Spam Clean User": "Spam opruimen gebruiker",
    "Delete private conversations": "Privégesprekken verwijderen",
    "Ban the user account": "Gebruikersaccount blokkeren",
    "Handled threads": "Onderwerpen afgehandeld",
    "Deleted messages": "Berichten verwijderd",
    "Deleted conversations": "Gesprekken verwijderd",
    "Banned user": "Gebruiker geblokkeerd",
    "Successfully cleaned spam for {username}. Actions: {actions}": "Spam succesvol opgeruimd voor {username}. Acties: {actions}",
    "Error loading message: {error}": "Fout bij laden van bericht: {error}",
    "Message not found": "Bericht niet gevonden",
    "Home": "Start",
    "Notifications": "Meldingen",
    "Forums": "Forums",
    "Mark All Forums as Read?": "Alle forums als gelezen markeren?",
    "This will mark all forums and topics as read. This action cannot be undone.": "Dit markeert alle forums en onderwerpen als gelezen. Deze actie kan niet ongedaan worden gemaakt.",
    "Mark as Read": "Als gelezen markeren",
    "Content": "Inhoud",
    "Insert Image": "Afbeelding invoegen",
    "How would you like to insert this image?": "Hoe wilt u deze afbeelding invoegen?",
    "Thumbnail": "Miniatuur",
    "Full Size": "Volledige grootte",
    "Align Left": "Links uitlijnen",
    "Align Center": "Centreren",
    "Align Right": "Rechts uitlijnen",
    "Please enter a title": "Voer een titel in",
    "Please enter some content": "Voer inhoud in",
    "Uploading...": "Uploaden...",
    "Uploaded": "Geüpload",
    "Mention User": "Gebruiker vermelden",
    "Logging in...": "Inloggen...",
    "Submitting report...": "Melding verzenden...",
    "Banning user...": "Gebruiker blokkeren...",
    "Unbanning user...": "Blokkering opheffen...",
    "Cleaning spam...": "Spam opruimen...",
    "Enter subject": "Voer onderwerp in",
    "Type your message here": "Typ hier uw bericht",
    "Write your message...": "Schrijf uw bericht...",
    "Write your reply...": "Schrijf uw antwoord...",
    "Message sent successfully": "Bericht succesvol verzonden",
    "Reply sent successfully": "Antwoord succesvol verzonden",
    "Conversation created successfully": "Gesprek succesvol aangemaakt",
    "Conversation marked as unread": "Gesprek als ongelezen gemarkeerd",
    "Message marked as unread": "Bericht als ongelezen gemarkeerd",
    "Conversation closed": "Gesprek gesloten",
    "Conversation opened": "Gesprek geopend",
    "Please login to like messages": "Log in om berichten te liken",
    "Load Earlier Messages": "Eerdere berichten laden",
    "Failed to load quote: \n{error}": "Kon citaat niet laden: \n{error}",
    "Failed to upload file: {error}": "Kon bestand niet uploaden: {error}",
    "Failed to upload image: {error}": "Kon afbeelding niet uploaden: {error}",
    "Failed to send message: {error}": "Kon bericht niet verzenden: {error}",
    "Failed to send reply: {error}": "Kon antwoord niet verzenden: {error}",
    "Failed to mark message as unread: {error}": "Kon bericht niet als ongelezen markeren: {error}",
    "Failed to mark conversation as unread: {error}": "Kon gesprek niet als ongelezen markeren: {error}",
    "Failed to close conversation: {error}": "Kon gesprek niet sluiten: {error}",
    "Failed to open conversation: {error}": "Kon gesprek niet openen: {error}",
    "Failed to jump to message: {error}": "Kon niet naar bericht springen: {error}",
    "Go to top": "Naar boven",
    "Go to bottom": "Naar beneden",
    "Reply All": "Allen beantwoorden",
    "Forward": "Doorsturen",
    "No forums found.": "Geen forums gevonden.",
    "Please select a prefix": "Selecteer een voorvoegsel",
    "Please login to access this content and interact with posts.": "Log in om deze inhoud te bekijken en te reageren op berichten.",
    "Search users...": "Gebruikers zoeken...",
    "Write your title...": "Schrijf uw titel...",
    "Write your content...": "Schrijf uw inhoud...",
    "Select an option": "Selecteer een optie",
    "Enter conversation title": "Voer gesprekstitel in",
    "Enter {count}-digit code": "Voer {count}-cijferige code in",
    "Edit": "Bewerken",
    "Report": "Melden",
    "Unfollow": "Ontvolgen",
    "Follow": "Volgen",
    "Go to Forums": "Naar forums",
    "Remove": "Verwijderen",
    "Subject": "Onderwerp",
    "Message": "Bericht",
    "Title cannot be empty": "Titel mag niet leeg zijn",
    "Conversation updated successfully": "Gesprek succesvol bijgewerkt",
    "Go Back": "Terug",
    "Private messages not available": "Privéberichten niet beschikbaar",
    "Failed to load post: \n{error}": "Kon bericht niet laden: \n{error}",
    "Failed to {action} message: {error}": "Kon bericht niet {action}: {error}",
    "like": "liken",
    "unlike": "unliken",
    "Optimize Image": "Afbeelding optimaliseren",
    "Optimize and Upload": "Optimaliseren en uploaden",
    "Downloading {filename}...": "Downloaden {filename}...",
    "Opening share sheet for {filename}": "Deelmenu openen voor {filename}",
    "Error downloading {filename}: {error}": "Fout bij downloaden {filename}: {error}",
    "Enter a number": "Voer een getal in",
    "Failed to navigate to forum": "Kon niet naar forum navigeren",
    "Failed to navigate to {forumName}": "Kon niet navigeren naar {forumName}",
    "Forum not found: {forumName}": "Forum niet gevonden: {forumName}",
    "Forum not found: {forumId}": "Forum niet gevonden: {forumId}",
    "Could not open link: {error}": "Kon link niet openen: {error}",
    "Like post": "Bericht liken",
    "Unlike post": "Bericht unliken",
    "Thank post": "Bericht bedanken",
    "Show likes": "Likes tonen",
    "Show thanks": "Bedankingen tonen",
    "Quote post": "Bericht citeren",
    "Attach file": "Bestand bijvoegen",
    "Upload image": "Afbeelding uploaden",
    "Translate": "Vertalen",
    "Show Original": "Origineel tonen",
    "Translating...": "Vertalen...",
    "Translated": "Vertaald",
    "Translated content": "Vertaalde inhoud",
    "Select Language": "Taal selecteren",
    "Translate to:": "Vertalen naar:",
    "Device language": "Apparaattaal",
    "No posts to translate": "Geen berichten om te vertalen",
    "Translation failed": "Vertalen mislukt",
}


def translate(s: str) -> str:
    return TRANSLATIONS.get(s, s)


def main():
    with open(EN_ARB, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    out = []
    for line in lines:
        if '"@@locale": "en"' in line:
            out.append(line.replace('"en"', '"nl"'))
            continue
        # Match "  "key": "value", or "  "key": "value"
        m = re.match(r'(\s*"[^"]+"\s*:\s*)"([^"]*)"(\s*,?\s*)$', line)
        if m:
            prefix, value, suffix = m.groups()
            # Only translate if key (in prefix) does not start with @ (metadata)
            key_match = re.search(r'"([^"]+)"', prefix)
            if key_match and not key_match.group(1).startswith('@'):
                out.append(f'{prefix}"{translate(value)}"{suffix}')
            else:
                out.append(line)
        else:
            out.append(line)

    with open(NL_ARB, 'w', encoding='utf-8') as f:
        f.writelines(out)
    print(f'Wrote {NL_ARB}')


if __name__ == '__main__':
    main()
