import 'dart:convert';
import 'package:forumcopilot_sdk/context/site_context.dart';
import 'package:forumcopilot_sdk/interfaces/i_fc_config_proxy.dart';
import 'package:forumcopilot_sdk/models/results/fc_config_result.dart';
import '../base_xenforo_proxy.dart';

/// XenForo implementation of IFCConfigProxy
/// Handles forum configuration retrieval for XenForo forums
class XenForoConfigProxy extends BaseXenForoProxy implements IFCConfigProxy {
  XenForoConfigProxy(SiteContext context) : super(context);

  @override
  Future<FCConfigResult> getConfig(String url, {bool forceRefresh = false}) async {
    print('✅ [XENFORO_CONFIG] getConfig called via plugin API');
    print('   📋 Parameters: url=$url, forceRefresh=$forceRefresh');

    try {
      siteContext.lastGetConfigFcIsLogin = null;
      // Call plugin API with getConfig method
      final response = await callPluginApi('getConfig', {
        'url': url,
        'forceRefresh': forceRefresh,
      });

      final fcIsLoginFromThisGetConfig =
          response.remove('_fc_plugin_internal_fc_is_login') as bool? ?? false;
      siteContext.lastGetConfigFcIsLogin = fcIsLoginFromThisGetConfig;

      // Log the full JSON response for debugging
      print('✅ [XENFORO_CONFIG] getConfig response:');
      print('   📋 Full JSON response (formatted):');
      // Pretty print the JSON response
      try {
        final encoder = JsonEncoder.withIndent('  ');
        print(encoder.convert(response));
      } catch (e) {
        print('   ${response.toString()}');
      }

      // Convert response to FCConfigResult
      return FCConfigResult(
        jsonSupport: response['jsonSupport'] ?? true,
        systemVersion: response['systemVersion'] ?? '2.0',
        version: response['version'] ?? '2.0',
        hookVersion: response['hookVersion'] ?? '1.0',
        apiLevel: response['apiLevel'] ?? '4',
        releaseTimestamp: response['releaseTimestamp'] ?? DateTime.now().millisecondsSinceEpoch.toString(),
        pushSlug: response['pushSlug'] ?? 'xenforo',
        smartBannerInfo: response['smartBannerInfo'] ?? '',
        setForumInfo: response['setForumInfo'] ?? true,
        isOpen: response['isOpen'] ?? true,
        guestOkay: response['guestOkay'] ?? true,
        reportPost: response['reportPost'] ?? true,
        reportPm: response['reportPm'] ?? true,
        gotoPost: response['gotoPost'] ?? true,
        gotoUnread: response['gotoUnread'] ?? true,
        getTopicByIds: response['getTopicByIds'] ?? true,
        markRead: response['markRead'] ?? true,
        markForum: response['markForum'] ?? true,
        subscribeForum: response['subscribeForum'] ?? true,
        disableSubscribeForum: response['disableSubscribeForum'] ?? false,
        disableSearch: response['disableSearch'] ?? false,
        getLatestTopic: response['getLatestTopic'] ?? true,
        getNewTopic: response['getNewTopic'] ?? true,
        getIdByUrl: response['getIdByUrl'] ?? true,
        getUrlById: response['getUrlById'] ?? true,
        deleteReason: response['deleteReason'] ?? true,
        modApprove: response['modApprove'] ?? true,
        modDelete: response['modDelete'] ?? true,
        modReport: response['modReport'] ?? true,
        guestSearch: response['guestSearch'] ?? true,
        anonymous: response['anonymous'] ?? false,
        guestWhosOnline: response['guestWhosOnline'] ?? true,
        searchId: response['searchId'] ?? true,
        avatar: response['avatar'] ?? true,
        pmLoad: response['pmLoad'] ?? true,
        subscribeLoad: response['subscribeLoad'] ?? true,
        subscribeTopicMode: response['subscribeTopicMode'] ?? 'email',
        subscribeForumMode: response['subscribeForumMode'] ?? 'email',
        minSearchLength: response['minSearchLength'] ?? 3,
        inboxStat: response['inboxStat'] ?? true,
        multiQuote: response['multiQuote'] ?? true,
        defaultSmilies: response['defaultSmilies'] ?? true,
        canUnread: response['canUnread'] ?? true,
        announcement: response['announcement'] ?? true,
        emoji: response['emoji'] ?? true,
        supportMd5: response['supportMd5'] ?? false,
        supportSha1: response['supportSha1'] ?? false,
        passwordType: response['passwordType'] ?? 'bcrypt',
        conversation: response['conversation'] ?? true,
        getForum: response['getForum'] ?? true,
        getTopicStatus: response['getTopicStatus'] ?? true,
        getParticipatedForum: response['getParticipatedForum'] ?? true,
        getForumStatus: response['getForumStatus'] ?? true,
        getSmilies: response['getSmilies'] ?? true,
        advancedHtml: response['advancedHtml'] ?? true,
        idToUrlRedirect: response['idToUrlRedirect'] ?? true,
        updateProfile: response['updateProfile'] ?? true,
        getMemberList: response['getMemberList'] ?? true,
        mGetInactiveUsers: response['mGetInactiveUsers'] ?? true,
        mApproveUser: response['mApproveUser'] ?? true,
        pollOptionsMaxCount: response['pollOptionsMaxCount'] ?? true,
        advancedOnlineUsers: response['advancedOnlineUsers'] ?? true,
        markPmUnread: response['markPmUnread'] ?? true,
        markPmRead: response['markPmRead'] ?? true,
        advancedSearch: response['advancedSearch'] ?? true,
        massSubscribe: response['massSubscribe'] ?? true,
        userId: response['userId'] ?? '',
        regUrl: response['regUrl'] ?? '$url/register',
        guestGroupId: response['guestGroupId'] ?? '1',
        phpVersion: response['phpVersion'] ?? '8.0',
        adsDisabledGroup: response['adsDisabledGroup'] ?? '',
        markTopicRead: response['markTopicRead'] ?? true,
        advancedDelete: response['advancedDelete'] ?? true,
        firstUnread: response['firstUnread'] ?? true,
        alert: response['alert'] ?? true,
        getActivity: response['getActivity'] ?? true,
        searchUser: response['searchUser'] ?? true,
        userRecommended: response['userRecommended'] ?? true,
        ignoreUser: response['ignoreUser'] ?? true,
        getIgnoredUsers: response['getIgnoredUsers'] ?? true,
        unban: response['unban'] ?? true,
        banExpires: response['banExpires'] ?? true,
        advancedMerge: response['advancedMerge'] ?? true,
        advancedMove: response['advancedMove'] ?? true,
        advancedEdit: response['advancedEdit'] ?? true,
        twoStep: response['twoStep'] ?? true,
        searchStartedBy: response['searchStartedBy'] ?? true,
        bannerControl: response['bannerControl'] ?? true,
        allowTrending: response['allowTrending'] ?? true,
        pushType: response['pushType'] ?? 'fcm',
        push: response['push'] ?? 'enabled',
        disableHtml: response['disableHtml'] ?? false,
        contentEncoding: response['contentEncoding'] ?? 'gzip',
        contentType: response['contentType'] ?? 'application/json',
        signIn: response['signIn'] ?? true,
        setApiKey: response['setApiKey'] ?? true,
        loginWithEmail: response['loginWithEmail'] ?? true,
        syncUser: response['syncUser'] ?? true,
        getContact: response['getContact'] ?? true,
        userSubscription: response['userSubscription'] ?? true,
        pushContentCheck: response['pushContentCheck'] ?? true,
        apiKey: response['apiKey'] ?? '',
        mbqFrameVersion: response['mbqFrameVersion'] ?? '1.0',
        forumType: response['forumType'] ?? 'xenforo',
      );
    } catch (e) {
      print('❌ [XENFORO_CONFIG] Error getting config: $e');

      // Return a minimal config on error
      return FCConfigResult(
        jsonSupport: true,
        systemVersion: '2.0',
        version: '2.0',
        hookVersion: '1.0',
        apiLevel: '4',
        releaseTimestamp: DateTime.now().millisecondsSinceEpoch.toString(),
        pushSlug: 'xenforo',
        smartBannerInfo: '',
        setForumInfo: true,
        isOpen: true,
        guestOkay: true,
        reportPost: true,
        reportPm: true,
        gotoPost: true,
        gotoUnread: true,
        getTopicByIds: true,
        markRead: true,
        markForum: true,
        subscribeForum: true,
        disableSubscribeForum: false,
        disableSearch: false,
        getLatestTopic: true,
        getNewTopic: true,
        getIdByUrl: true,
        getUrlById: true,
        deleteReason: true,
        modApprove: true,
        modDelete: true,
        modReport: true,
        guestSearch: true,
        anonymous: false,
        guestWhosOnline: true,
        searchId: true,
        avatar: true,
        pmLoad: true,
        subscribeLoad: true,
        subscribeTopicMode: 'email',
        subscribeForumMode: 'email',
        minSearchLength: 3,
        inboxStat: true,
        multiQuote: true,
        defaultSmilies: true,
        canUnread: true,
        announcement: true,
        emoji: true,
        supportMd5: false,
        supportSha1: false,
        passwordType: 'bcrypt',
        conversation: true,
        getForum: true,
        getTopicStatus: true,
        getParticipatedForum: true,
        getForumStatus: true,
        getSmilies: true,
        advancedHtml: true,
        idToUrlRedirect: true,
        updateProfile: true,
        getMemberList: true,
        mGetInactiveUsers: true,
        mApproveUser: true,
        pollOptionsMaxCount: true,
        advancedOnlineUsers: true,
        markPmUnread: true,
        markPmRead: true,
        advancedSearch: true,
        massSubscribe: true,
        userId: '',
        regUrl: '$url/register',
        guestGroupId: '1',
        phpVersion: '8.0',
        adsDisabledGroup: '',
        markTopicRead: true,
        advancedDelete: true,
        firstUnread: true,
        alert: true,
        getActivity: true,
        searchUser: true,
        userRecommended: true,
        ignoreUser: true,
        getIgnoredUsers: true,
        unban: true,
        banExpires: true,
        advancedMerge: true,
        advancedMove: true,
        advancedEdit: true,
        twoStep: true,
        searchStartedBy: true,
        bannerControl: true,
        allowTrending: true,
        pushType: 'fcm',
        push: 'enabled',
        disableHtml: false,
        contentEncoding: 'gzip',
        contentType: 'application/json',
        signIn: true,
        setApiKey: true,
        loginWithEmail: true,
        syncUser: true,
        getContact: true,
        userSubscription: true,
        pushContentCheck: true,
        apiKey: '',
        mbqFrameVersion: '1.0',
        forumType: 'xenforo',
      );
    }
  }
}
