import 'package:forumcopilot_sdk/models/results/fc_config_result.dart';
import '../data/config/config.dart';

/// Converter for XenForo configuration data to FCConfigResult
class XenForoConfigConverter {
  /// Convert XenForo config to FCConfigResult
  static FCConfigResult toFCConfigResult(XenForoConfig xenForoConfig, String url) {
    return FCConfigResult(
      // Basic configuration
      jsonSupport: true,
      systemVersion: xenForoConfig.versionId,
      version: xenForoConfig.versionString,
      hookVersion: '1.0',
      apiLevel: '4',
      releaseTimestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      pushSlug: 'xenforo',
      smartBannerInfo: '',
      setForumInfo: true,
      isOpen: !xenForoConfig.maintenanceMode,
      guestOkay: true,

      // Forum features
      reportPost: true,
      reportPm: true,
      gotoPost: true,
      gotoUnread: true,
      getTopicByIds: true,
      markRead: true,
      markForum: true,
      subscribeForum: true,
      disableSubscribeForum: false,
      disableSearch: false,
      getLatestTopic: true,
      getNewTopic: true,
      getIdByUrl: true,
      getUrlById: true,
      deleteReason: true,
      modApprove: true,
      modDelete: true,
      modReport: true,
      guestSearch: true,
      anonymous: false,
      guestWhosOnline: true,
      searchId: true,
      avatar: true,
      pmLoad: true,
      subscribeLoad: true,
      subscribeTopicMode: 'email',
      subscribeForumMode: 'email',
      minSearchLength: 3,
      inboxStat: true,
      multiQuote: true,
      defaultSmilies: true,
      canUnread: true,
      announcement: true,
      emoji: true,
      supportMd5: false,
      supportSha1: false,
      passwordType: 'bcrypt',
      conversation: true,
      getForum: true,
      getTopicStatus: true,
      getParticipatedForum: true,
      getForumStatus: true,
      getSmilies: true,
      advancedHtml: true,
      idToUrlRedirect: true,
      updateProfile: true,
      getMemberList: true,
      mGetInactiveUsers: true,
      mApproveUser: true,
      pollOptionsMaxCount: true,
      advancedOnlineUsers: true,
      markPmUnread: true,
      markPmRead: true,
      advancedSearch: true,
      massSubscribe: true,
      userId: '',
      regUrl: '$url/register',
      guestGroupId: '1',
      phpVersion: '8.0',
      adsDisabledGroup: '',
      markTopicRead: true,
      advancedDelete: true,
      firstUnread: true,
      alert: true,
      getActivity: true,
      searchUser: true,
      userRecommended: true,
      ignoreUser: true,
      getIgnoredUsers: true,
      unban: true,
      banExpires: true,
      advancedMerge: true,
      advancedMove: true,
      advancedEdit: true,
      twoStep: true,
      searchStartedBy: true,
      bannerControl: true,
      allowTrending: true,
      pushType: 'fcm',
      push: 'enabled',
      disableHtml: false,
      contentEncoding: 'gzip',
      contentType: 'application/json',
      signIn: true,
      setApiKey: true,
      loginWithEmail: true,
      syncUser: true,
      getContact: true,
      userSubscription: true,
      pushContentCheck: true,
      apiKey: '', // Will be set from siteContext
      mbqFrameVersion: '1.0',
      forumType: 'xenforo',
    );
  }
}
